const supplements = [
  {
    name: "Protein powder",
    aliases: "Whey, casein, soy protein",
    goal: "Tăng cơ",
    evidence: "Bằng chứng tốt",
    summary: "Cách tiện lợi để đạt tổng protein ngày khi bữa ăn chưa đủ; không vượt trội hơn thực phẩm nếu tổng protein đã tương đương.",
    usage: "Một khẩu phần thường cung cấp 20–40g protein. Điều chỉnh theo phần protein còn thiếu trong ngày.",
    caution: "Kiểm tra dị ứng sữa/đậu nành, lượng đường và tổng calo. Không bắt buộc nếu chế độ ăn đã đủ protein.",
  },
  {
    name: "Creatine monohydrate",
    aliases: "Creatine",
    goal: "Tăng cơ",
    evidence: "Bằng chứng tốt",
    summary: "Hỗ trợ sức mạnh, công suất lặp lại và tăng khối nạc khi kết hợp tập kháng lực. Đây là dạng creatine được nghiên cứu nhiều nhất.",
    usage: "3–5g mỗi ngày, dùng đều. Có thể không cần giai đoạn loading; thời điểm uống ít quan trọng hơn tính đều đặn.",
    caution: "Có thể tăng cân nhẹ do nước trong cơ. Người có bệnh thận hoặc đang điều trị bệnh nên hỏi bác sĩ trước khi dùng.",
  },
  {
    name: "Caffeine",
    aliases: "Cà phê, pre-workout",
    goal: "Hiệu suất",
    evidence: "Bằng chứng tốt",
    summary: "Có thể tăng sự tỉnh táo và hiệu suất trong một số hoạt động sức bền hoặc cường độ cao.",
    usage: "Bắt đầu thấp, khoảng 1–3mg/kg trước tập 30–60 phút. Tính cả caffeine từ cà phê, trà và nước tăng lực.",
    caution: "Có thể gây mất ngủ, tim đập nhanh, lo âu và lệ thuộc. Tránh dùng gần giờ ngủ; không tự tăng liều để chạy theo cảm giác.",
  },
  {
    name: "Beta-alanine",
    aliases: "Beta alanine",
    goal: "Hiệu suất",
    evidence: "Bằng chứng khá",
    summary: "Có thể hỗ trợ các nỗ lực cường độ cao kéo dài khoảng 1–4 phút; tác dụng không đến ngay sau một lần uống.",
    usage: "Thường dùng tổng 3.2–6.4g/ngày trong nhiều tuần, chia liều nhỏ.",
    caution: "Cảm giác châm chích da khá phổ biến và thường giảm khi chia nhỏ liều. Không phải chất đốt mỡ.",
  },
  {
    name: "Nitrate / beetroot",
    aliases: "Nước ép củ dền",
    goal: "Hiệu suất",
    evidence: "Bằng chứng khá",
    summary: "Có thể cải thiện hiệu quả vận động và sức bền ở một số người, nhưng đáp ứng khác nhau giữa cá nhân.",
    usage: "Ưu tiên sản phẩm ghi rõ lượng nitrate thay vì chỉ ghi khối lượng bột củ dền.",
    caution: "Có thể làm nước tiểu hoặc phân đỏ. Người dùng thuốc huyết áp nên hỏi chuyên gia y tế.",
  },
  {
    name: "Electrolytes",
    aliases: "Natri, kali, magie",
    goal: "Sức khỏe",
    evidence: "Theo tình huống",
    summary: "Hữu ích khi tập kéo dài, ra nhiều mồ hôi hoặc trong thời tiết nóng; buổi tập ngắn thường chỉ cần nước và bữa ăn bình thường.",
    usage: "Ưu tiên bổ sung theo lượng mồ hôi và natri mất đi, không mặc định dùng càng nhiều càng tốt.",
    caution: "Người có bệnh tim, thận, huyết áp hoặc dùng thuốc ảnh hưởng điện giải cần hỏi bác sĩ.",
  },
  {
    name: "Vitamin D",
    aliases: "Vitamin D3",
    goal: "Sức khỏe",
    evidence: "Theo thiếu hụt",
    summary: "Quan trọng cho xương và chức năng cơ, nhưng bổ sung thêm không tự động làm tăng cơ nếu bạn không thiếu vitamin D.",
    usage: "Nên dựa trên chế độ ăn, phơi nắng, nguy cơ thiếu hụt và xét nghiệm/chỉ định chuyên môn.",
    caution: "Vitamin D tích lũy được; liều cao kéo dài có thể gây độc. Không tự dùng megadose.",
  },
  {
    name: "Omega-3",
    aliases: "EPA, DHA, dầu cá",
    goal: "Sức khỏe",
    evidence: "Theo chế độ ăn",
    summary: "Có vai trò với sức khỏe tim mạch; không phải chất tăng cơ hay giảm mỡ trực tiếp. Cá béo là nguồn thực phẩm ưu tiên.",
    usage: "Xem xét khi khẩu phần hiếm khi có cá béo; đọc lượng EPA+DHA thay vì chỉ nhìn tổng mg dầu cá.",
    caution: "Liều cao có thể ảnh hưởng chảy máu và tương tác thuốc chống đông; hỏi bác sĩ nếu đang điều trị.",
  },
  {
    name: "BCAA",
    aliases: "Leucine, isoleucine, valine",
    goal: "Tăng cơ",
    evidence: "Ít cần thiết",
    summary: "Nếu tổng protein và protein chất lượng cao đã đủ, BCAA thường không mang thêm lợi ích rõ ràng cho tăng cơ.",
    usage: "Ưu tiên bữa ăn giàu protein hoặc protein hoàn chỉnh thay vì mua BCAA riêng.",
    caution: "Không thay thế được tổng protein, calo và chương trình tập phù hợp.",
  },
  {
    name: "Glutamine",
    aliases: "L-glutamine",
    goal: "Tăng cơ",
    evidence: "Bằng chứng yếu",
    summary: "Chưa cho thấy lợi ích tăng cơ hoặc sức mạnh đáng kể ở người khỏe mạnh đã ăn đủ protein.",
    usage: "Không phải ưu tiên cho mục tiêu hypertrophy thông thường.",
    caution: "Đừng nhầm ứng dụng y khoa đặc thù với lợi ích tăng cơ cho người khỏe mạnh.",
  },
  {
    name: "L-carnitine",
    aliases: "Carnitine",
    goal: "Giảm mỡ",
    evidence: "Bằng chứng hạn chế",
    summary: "Không phải fat burner đáng tin cậy cho đa số người khỏe mạnh; hiệu quả giảm cân nếu có thường nhỏ và không thay thế deficit.",
    usage: "Không nên xem là nền tảng của kế hoạch giảm mỡ.",
    caution: "Có thể gây khó chịu tiêu hóa và mùi cơ thể ở một số người.",
  },
  {
    name: "CLA",
    aliases: "Conjugated linoleic acid",
    goal: "Giảm mỡ",
    evidence: "Bằng chứng yếu",
    summary: "Kết quả giảm mỡ không nhất quán và mức thay đổi thường nhỏ, không đáng để thay thế kiểm soát calo và vận động.",
    usage: "Không phải lựa chọn ưu tiên.",
    caution: "Có thể gây khó chịu tiêu hóa; một số liều/sản phẩm có thể ảnh hưởng chuyển hóa.",
  },
  {
    name: "Fat burner blends",
    aliases: "Thermogenic, proprietary blend",
    goal: "Giảm mỡ",
    evidence: "Nên tránh",
    summary: "Thường là hỗn hợp stimulant với bằng chứng yếu, liều không minh bạch và hiệu quả giảm mỡ nhỏ.",
    usage: "Deficit calo, protein, tập kháng lực, bước chân và giấc ngủ vẫn là nền tảng.",
    caution: "Có thể gây tim đập nhanh, tăng huyết áp, lo âu hoặc tương tác thuốc. Tránh proprietary blend không ghi rõ liều.",
  },
  {
    name: "SARMs / prohormones / steroid",
    aliases: "Chất tăng cơ không phải supplement thông thường",
    goal: "Tăng cơ",
    evidence: "Không khuyến nghị",
    summary: "Đây không phải nhóm thực phẩm bổ sung an toàn. Có nguy cơ nội tiết, gan, tim mạch, sinh sản và sản phẩm có thể sai nhãn.",
    usage: "Không tự sử dụng để tăng cơ hoặc giảm mỡ.",
    caution: "Cần tư vấn y tế; sản phẩm bán dưới nhãn supplement không làm chúng trở nên an toàn hoặc hợp pháp.",
  },
];

export { supplements };
